<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Configurations>LabApi</Configurations>
    <Configuration Condition="'$(Configuration)' == ''">LabApi</Configuration>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Authors>icedchqi</Authors>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <NoWarn>$(NoWarn);NU1902</NoWarn>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SecretLabNAudio.Core" Version="2.1.2" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
    <PackageReference Include="Northwood.LabAPI" Version="1.1.7" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp-Publicized">
      <HintPath>$(sl_references)\Assembly-CSharp-Publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(sl_references)\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <HintPath>$(sl_references)\CommandSystem.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>$(sl_references)\Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Pooling">
      <HintPath>$(sl_references)\Pooling.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="NorthwoodLib">
      <HintPath>$(sl_references)\NorthwoodLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(sl_references)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(sl_references)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
